# Site settings
title: Jedike Mon Chay
email: "jedikemonchay@gmail.com"
description: "Photo Journal"
url: "https://tapaspal9.github.io"
baseurl: "/jmc"
facebook_username: "jedikemonchay"
#twitter_username: ""
instagram_username: "jedikemonchay19"
#github_username:  ""
#deviantart_username: ""
#flickr_username: ""
#discus_shortname: ""
youtube_username: "jedikemonchay6784"
share: true

# Owner/author information
owner:
  name:   photorama
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://tapaspal9.github.io/jmc/gallery/"  
  - JOURNAL: "https://tapaspal9.github.io/jmc/journal/"
  - ABOUT: "https://tapaspal9.github.io/jmc/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
